version: '3.7'

services:
    frontend:
        build: ./frontend #Lanzar contenedor
        container_name: "frontend"
        ports:
            - 3000:3000
        depends_on: 
            - backend
    backend:
        build: ./backend #Lanzar contenedor
        container_name: "backend"
        ports: 
            - 5000:5000
        depends_on: 
            - mysql
        command: "npm run dev"
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'trauma_simulator'
            # Password for root access
            MYSQL_ROOT_PASSWORD: '1234'
        ports: 
            - 3307:3306
        expose:
            # Opens port 3306 on the container
            - '3307'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
    # Names our volume
volumes:
    my-db:

