version: '3.7'

services:
    frontend:
        tty: true
        build: ./frontend #Lanzar contenedor
        container_name: "frontend"
        ports:
            - 3000:3000
        depends_on: 
            - backend
    backend:
        tty: true
        build: ./backend #Lanzar contenedor
        container_name: "backend"
        ports: 
            - 8080:8080
        depends_on: 
            - mysql
        
    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'trauma_simulator'
            
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'luis110797'
        ports: 
            - 3307:3306
        expose:
            # Opens port 3306 on the container
            - '3307'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
    # Names our volume
volumes:
    my-db:

